name: flutter_demo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: 4.0.5
  flutter_launcher_icons: 0.11.0
  whatsapp_unilink: 2.1.0
  url_launcher: 6.1.9
  local_auth: 2.1.3
  connectivity_plus: 3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - lang/
